version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "proposal-processor-v2"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "AWSAccountId=985803916100"
s3_bucket = ""  # Will be provided by GitHub Actions
resolve_s3 = true