version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "csv-to-parquet-processor"
resolve_image_repos = true
confirm_changeset = false
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = ["ProcessingFunction=processingfunction"]